name: clashy build

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build: [
          {name: clashy-linux, platform: linux/amd64, os: ubuntu-latest},
          {name: clashy, platform: windows/amd64, os: windows-latest},
          {name: clashy, platform: darwin/universal, os: macos-latest}
        ]
    runs-on: ${{ matrix.build.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: pnpm/action-setup@0609f0983b7a228f052f81ef4c3d6510cae254ad
        with:
          version: 6.10.0
      - uses: dAppServer/wails-build-action@v2.2
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          go-version: '1.22'
          wails-build-webview2: embed
