---
name: RoutuneDash build

on:
  push:
    tags:
      - '*'

permissions:
  contents: write
  discussions: write
  packages: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build:
          - name: 'RoutuneDash-linux'
            platform: 'linux/amd64'
            os: 'ubuntu-latest'
          - name: 'RoutuneDash'
            platform: 'windows/amd64'
            os: 'windows-latest'
          - name: 'RoutuneDash'
            platform: 'darwin/universal'
            os: 'macos-latest'
    runs-on: ${{ matrix.build.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: dAppServer/wails-build-action@v2.2
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          go-version: '1.22'
          node-version: '20.x'
          wails-build-webview2: embed
